name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Install packages  
        run: pnpm install
      - name: Run client linters checks
        run: pnpm lint
      - name: Run tests
        run: pnpm test