name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install packages  
        run: pnpm install
      - name: Run client linters checks
        run: pnpm lint
      - name: Run unit tests
        run: pnpm vitest run 
      - name: Run integrations tests
        run: pnpm exec playwright install && pnpm playwright test